### ISSUE TITLE
list of games played by given gamertag

### ISSUE THREAD

**Issue by mathieujobin** [glebb/eashl#1]
hey @glebb 

have you ever found an EASports API such that I could fetch all the game stats for a given PS4/XboxOne gamertag?

or do you know if EASports has a paying API service of such sort?

thanks

**Comment by glebb** [comment]
Hey. As this project pretty much died before nhl 17 came out, I haven't really been looking into if there's new public/web api's to be consumed now. I don't think there was such api earlier, and I'm not aware of any paying API service either. That would be cool though (even better if it would be open for all). I think the devs behind https://nhlgamer.com/ might be more up to date on what's happening in easports nhl regarding api's and such. At least there was some talk about it on the forum: https://nhlgamer.com/community/news/nhlgamer/feature-release-stats-api-r114/ I haven't been in contact with them directly though.
